### ISSUE TITLE
Switch from istream.useNormalizer(f) to useCalibrator(f).

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#100]
That is, useCalibrator() should take either a calibrator object or a simple function of the sort that istream::useNormalizer currently accepts (i.e. from vector<double> to vector<double> or from double to double).

**Comment by damellis** [comment]
The calibrator's normalization function should only be called if the calibration samples have been collected.

**Comment by damellis** [comment]
The normalization function should be passed to the Calibrator's constructor. Don't require a separate call to stream.useNormalizer().

**Comment by nebgnahz** [comment]
Integrated into the new `Calibrator` class. I am not dropping the `useNormalizer` inside `istream` because it's not necessary at this stage.
