### ISSUE TITLE
Support multiple calibration samples within a single Calibrator object.

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#101]
We probably want to specify multiple calibration samples within a single calibrator object, all of which can share a single function for actually doing the calibration (once all the samples are collected). This may need to be done through member functions (e.g. addCalibrationSample(name, description, callback)) with perhaps a shortcut for specifying a single (or the first) calibration sample directly in the constructor.

**Comment by nebgnahz** [comment]
Updated the implementation.

The basic idea is change previous `Calibrator` as `CalibrateProcess` and manage the list of `CalibrateProcess` inside `Calibrator`.

For an example of what it looks like, see `user_accelerometer_calibration.h`.
