### ISSUE TITLE
Collapse, don't hide, parameter tuning panel.

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#102]
Show as a clickable dropdown in the tab bar at the top.

**Comment by nebgnahz** [comment]
See https://github.com/damellis/sensors/commit/eb95d807166b7b2e3fe036fd9b36445be39c65be.
There is an open issue (https://github.com/braitsch/ofxDatGui/issues/57) of how to collapse it by default instead of being opened. I will follow up on this.
