### ISSUE TITLE
Support calibrate functions of the form "double f(double)".

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#109]
As in the normalizer, the user should be able to specify a function that operates on one dimension at a time, and we should iterate over all the dimensions and call that function for each one. For instance, the processAccelerometerData() function in user_accelerometer_calibration could be just:

````
double processAccelerometerData(double input)
{
    return (input - zeroG) / (oneG - zeroG);
}
````

**Comment by nebgnahz** [comment]
Implemented: https://github.com/damellis/sensors/commit/85a77d2644b705cc25f37bd19d375261c689d13d.
