### ISSUE TITLE
On recalibration, use uncalibrated data as input to calibration samples.

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#112]
That is, the calibration samples should draw on raw data, not calibrated data.

**Comment by nebgnahz** [comment]
This commit https://github.com/damellis/sensors/commit/727df6bdfd18239aa464f7e23319b861ccf46ac6 fixes it.

The idea is to separate `raw_data` from `data_point`.

One consequence of this commit is that if calibrator exists but the data has not been calibrated, the tab is forced to `CALIBRATION` tab.
