### ISSUE TITLE
Show calibration-specific instructions on calibration tab.

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#117]
e.g. what the purpose of the calibration tab is and how to record calibration samples. (Note this is different from showing the descriptions for each calibration sample, which we should also do.)

**Comment by nebgnahz** [comment]
Fixed by https://github.com/damellis/sensors/commit/de832464df7e6bee75158ac558b5f705b46220ba.

Plotter has a subtitle (default empty string); show instructions as subtitles.

**Comment by nebgnahz** [comment]
Addressed in https://github.com/damellis/sensors/commit/62e63bcba5ad626fa2cde109b8af8f6c0a1db55a.

Partially duplicated with https://github.com/damellis/sensors/issues/137.
