### ISSUE TITLE
Accelerometer calibration may need to invert z-axis value.

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#124]
e.g. the read we get when the device is flat on the table may be -1G, not 1G. Need to check between different accelerometers. Or maybe just compare it to the 0G axis values.

**Comment by nebgnahz** [comment]
See https://github.com/damellis/sensors/commit/bf3049178e891b0b4b8e363d357eaa5288b9f680.

Not sure if this is what you @damellis have in mind.

**Comment by damellis** [comment]
I reverted this, as I think it was actually correct before and I was just confused. We do want to distinguish between positive Z and negative Z (right-side up vs. upside down), so we shouldn't use abs(). I think I was confused about the effect of gravity.
