### ISSUE TITLE
Program crashes if remote end of TCP OStream disconnects.

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#129]
This is something we should probably fix because it means you lose your training data.

**Comment by nebgnahz** [comment]
Previously messages are sent with `write` syscall to a file descriptor. Operating at socket level is known hard.

New commit (https://github.com/damellis/sensors/commit/854727a83b1a0ed4e5a0fdb194643e20653c5701) uses `ofxTCPClient` to simplify the process.
