### ISSUE TITLE
first-time setup script

### ISSUE THREAD

**Issue by elsehow** [damellis/sensors#131]
i think there should be a one-step script for first-time setup. so, someone can just clone the repo and 

`./setup`

here's the script i made from the README directions (running now, will report back)

```shell
#!/bin/bash

git submodule init
git submodule update
ln -s $(pwd)/third-party/ofxGrt/ third-party/openFrameworks/addons/ofxGrt
ln -s $(pwd)/third-party/ofxDatGui/ third-party/openFrameworks/addons/ofxDatGui
ln -s $(pwd)/third-party/ofxParagraph/ third-party/openFrameworks/addons/ofxParagraph

cd third-party/grt/build
mkdir tmp
cd tmp
cmake ..
make
sudo make install
```

one thing i'd like to include is this tip from the readme:

`git submodule update --depth 1 -- third-party/openFrameworks`

this seems like a sensible default. 
how should it be incorporated into the script above?

**Comment by damellis** [comment]
That sounds good. Maybe including the openFrameworks depth 1 line before the regular git submodule update line will do the right thing? A pull request would be great!

**Comment by damellis** [comment]
Merged!

**Comment by elsehow** [comment]
@damellis hooray! thanks. could you add some note to the readme about how to get up-and-running after setup?

**Comment by damellis** [comment]
Will do.
