### ISSUE TITLE
Incorrect scaling of features showing on training tab.

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#135]
For example (accelerometer_poses):

![screen shot 2016-04-18 at 2 56 06 pm](https://cloud.githubusercontent.com/assets/405058/14621194/f914ebee-0575-11e6-9758-1e4fcd9de111.png)

I'm not quite sure what's going on here.

**Comment by nebgnahz** [comment]
This might be due to `setRanges` that modifies `min_Y_` or `default_min_Y_` (I will look into this tonight).

**Comment by nebgnahz** [comment]
This is fixed by https://github.com/damellis/sensors/commit/838527f7fc8b52bdee81eabb9391d50557ca301e.

The cause is double ranges are rounded to integer in previous code.
