### ISSUE TITLE
Support plots that don't cover the whole x-axis range.

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#22]
That is, if the plot is 256 samples wide but the data only has 128 samples, just don't draw anything at all in the second half of the plot. Maybe we should fix this locally and then send a pull request upstream?

**Comment by damellis** [comment]
Fixed by ae4ee6ececd29bcb4c075051462152aa0da5005f in nebgnahz/ofxGrt

**Comment by nebgnahz** [comment]
Further improved by https://github.com/nebgnahz/ofxGrt/commit/a71b55a5ceee9a0d91731aaa641e9babfea38341.
