### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#25]
![exemplar](https://cloud.githubusercontent.com/assets/405058/12861928/dc628c4c-cc1b-11e5-9cdd-ecdb508aa075.png)

**Comment by nebgnahz** [comment]
It might be worth keeping this issues for assets loading (wiki, etc).

**Comment by damellis** [comment]
Sure, sounds good.

**Comment by nebgnahz** [comment]
![screen shot 2016-05-06 at 1 23 11 am](https://cloud.githubusercontent.com/assets/941519/15068071/a0e18aec-1329-11e6-9970-47da0e648da4.png)
![screen shot 2016-05-06 at 1 23 33 am](https://cloud.githubusercontent.com/assets/941519/15068072/a0f32928-1329-11e6-9577-f0a86b6836d8.png)
![screen shot 2016-05-06 at 1 24 20 am](https://cloud.githubusercontent.com/assets/941519/15068073/a0fc2a32-1329-11e6-8262-43fc18e0cd3f.png)

**Comment by nebgnahz** [comment]
![cmake-grt](https://cloud.githubusercontent.com/assets/941519/17238401/301f5ee6-5510-11e6-8587-429cd9f9a41c.PNG)

**Comment by nebgnahz** [comment]
![screen shot 2016-07-28 at 11 06 59 pm](https://cloud.githubusercontent.com/assets/941519/17239325/0eb7eac2-5518-11e6-822f-02a96775c804.png)

**Comment by damellis** [comment]
![esp](https://cloud.githubusercontent.com/assets/405058/17263390/b2aff8cc-5595-11e6-9886-60e92ed0dc22.png)

**Comment by damellis** [comment]
![sweepsenser](https://cloud.githubusercontent.com/assets/405058/17348588/ff6d94f6-58cb-11e6-9ad5-e218bba4c5ab.jpg)

**Comment by damellis** [comment]
![img_6678](https://cloud.githubusercontent.com/assets/405058/17499161/96e9f96a-5d80-11e6-86aa-52630ab37d9a.jpg)

**Comment by damellis** [comment]
![img_6685](https://cloud.githubusercontent.com/assets/405058/17499238/016ca6ca-5d81-11e6-92b7-3d0bcf0dc0c4.jpg)
