### ISSUE TITLE
Don't require external compilation of the GRT.

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#32]
We should either bundle a compiled version (as in newer version of the ofxGrt addon) or include the GRT in the Xcode project so that it's built automatically.

**Comment by nebgnahz** [comment]
We could optionally provide a shell script like `setup.sh` to ease the process of setting things up.

Currently users need to do submodule update and create a soft link for `ofxGrt`.

**Comment by damellis** [comment]
I think I fixed this. Note that to get the application we build to correctly link against the libgrt.dylib in its Frameworks/ directory, I needed to set the id of libgrt.dylib:

`install_name_tool -id @executable_path/../Frameworks/libgrt.dylib Xcode/SmartSensors/libgrt.dylib`

Apparently, when an executable is linked against a dynamic library, it remembers the id of the library and searches for it in that path when run.  See: https://github.com/conda/conda-build/issues/279

**Comment by damellis** [comment]
Closing for now. Note that we still need the GRT header files, so we should probably keep the GRT submodule. If we need to update the GRT regularly, we may want to switch to compiling the GRT as an Xcode project / target which can be a dependency of our main project.
