### ISSUE TITLE
Rename Audio Xcode project.

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#34]
To something more descriptive. Maybe just "sensors"? Or SmartSensors?

**Comment by nebgnahz** [comment]
Maybe the following:

Current
```
Xcode
├── Audio
│   ├── Audio.xcodeproj
│   ├── Makefile
│   ├── Project.xcconfig
│   ├── addons.make
│   ├── bin
│   ├── config.make
│   ├── obj
│   ├── openFrameworks-Info.plist
│   └── src
└── GUI
    ├── GUI.xcodeproj
    ├── Makefile
    ├── Project.xcconfig
    ├── addons.make
    ├── bin
    ├── config.make
    ├── openFrameworks-Info.plist
    └── src
```

Proposed
```
Xcode
├── SmartSensors
│   ├── SmartSensors.xcodeproj
│   ├── Makefile
│   ├── Project.xcconfig
│   ├── addons.make
│   ├── bin
│   ├── config.make
│   ├── obj
│   ├── openFrameworks-Info.plist
│   └── src
```

**Comment by damellis** [comment]
That is, get rid of the current "GUI" project and rename "Audio" to "SmartSensors"? Sounds good to me.

**Comment by nebgnahz** [comment]
Done.

- Remove "GUI" https://github.com/damellis/sensors/commit/fd34c8cb7e0a5edf5ffee2b2eb81cd14dfe4ec29
- Rename "Audio" to "SmartSensors"
https://github.com/damellis/sensors/commit/17319c65bcd3c3683308e210068da468fd5a2191
