### ISSUE TITLE
Label chart axes (w/ numeric values).

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#5]
For the raw data, pre-processed data, features, and training data.

**Comment by nebgnahz** [comment]
For Y-axis, this task is pending on [a pull request to ofxGrt](https://github.com/nickgillian/ofxGrt/pull/2).
For X-axis, not sure what to display.

**Comment by nebgnahz** [comment]
`Good to know... I think we may want to create our own fork of the GRT for development. We should still try to send changes upstream but I don't want to get stuck waiting for them to be merged. What do you think?`

Replying here:
Agree with our [own fork](https://github.com/nebgnahz/ofxGrt).

**Comment by damellis** [comment]
Great. I added you to my fork of the main GRT here: https://github.com/damellis/grt/

**Comment by nebgnahz** [comment]
this issue is resolved...
