### ISSUE TITLE
Show all features on same scale (in training tab).

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#62]
@nebgnahz I think it would be good to show all the features on the same scale, so you can get a sense of their absolute values, even though the scales differ between features. For instance, right now I'm looking at an example that uses mean and std. dev. as features and I can't tell how the mean and std. dev. compare because each is scaled separately. Which also makes it hard to compare data across classes. What do you think?

**Comment by nebgnahz** [comment]
As per discussion, the same scale is applied for the same feature (across classes, but not across features). I am marking this as closed, but we may discuss (and re-open) this further.
