### ISSUE TITLE
Class names lost when deleting or trimming training data samples.

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#65]
When I modify the training data and retrain the model, the class name no longer show up in the live pipeline view. Instead, "Label 1", etc are shown shown. The correct names are still shown in the training sample plots.
![screen shot 2016-03-07 at 2 40 05 pm](https://cloud.githubusercontent.com/assets/405058/13585761/85487b6e-e472-11e5-9691-876a9998c64c.png)

**Comment by nebgnahz** [comment]
Deleting calls `training_data_.eraseAllSamplesWithClassLabel(label);`, therefore the class name is also lost.

The commit (https://github.com/damellis/sensors/commit/bf3e6a7af1a09a930e28977dea533408fef1636e) fixes this.

**Comment by damellis** [comment]
I think this also happens when trimming samples.
