### ISSUE TITLE
Need to reset pipeline when calculating features of training samples.

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#67]
Otherwise the data at the end of one sample affects the features at the start of the next. Example data (w/ the accelerometer poses pipeline).

[TrainingData.grt.txt](https://github.com/damellis/sensors/files/162327/TrainingData.grt.txt)

**Comment by nebgnahz** [comment]
Done.
https://github.com/damellis/sensors/commit/dcfb17742a7dea76929e7fad18304d9737ad1b72
