### ISSUE TITLE
Indicate when training is happening / complete.

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#79]

**Comment by damellis** [comment]
Maybe a label somewhere that says "training..." while training is happening and disappears when it's done? So for quick training, you'd still at least see something flash by on the screen.

**Comment by nebgnahz** [comment]
Done with https://github.com/damellis/sensors/commit/ef840587bcc48d2ae8f5c27b8efa713eba00f9eb.

We can extend the status string for other purposes (such as https://github.com/damellis/sensors/issues/138, https://github.com/damellis/sensors/issues/88, https://github.com/damellis/sensors/issues/11).
