### ISSUE TITLE
Display legend for plots, giving a name for each data dimension?

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#83]
e.g. red line is x-axis, green is y-axis, blue is z-axis. This could be specified by the example author in the code.

**Comment by nebgnahz** [comment]
See https://github.com/damellis/sensors/commit/67db321d93fde3e2cc3c8b4dc35bcf530c4e48cb.

Example usage:

```
stream.setLabelsForAllDimensions({"x-axis", "y-axis", "z-axis"});
```

**Comment by damellis** [comment]
These seem easy to miss (especially the one letter ones like "x", "y", "z"). What do you think about replacing the "[1]: " at the start of the info text with "[x]: " or maybe "1. [x]: "?
