### ISSUE TITLE
Way to tune the post-processing parameters in the GUI.

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#86]
e.g. parameters for the ClassLabelFilter.

**Comment by nebgnahz** [comment]
@damellis 
Generalized to pipeline parameter. 

For an example, check out https://github.com/damellis/sensors/commit/e3c1e2b86332dd5fdc1e4a63fc6b8a3898321084.

**Comment by nebgnahz** [comment]
UI:
1. Type 'h' to open the "parameter tuning" panel.
2. Control the slider or click the button to change the value. Under the hood, a callback function `Tuneable::onXXXEvent` is invoked which will call `ofApp::reloadPipelineModules()`.

P.S. Shouldn't close this.... reopening.

**Comment by nebgnahz** [comment]
Closing this issue as parameter tuning is implemented. And update to previous comment:
1. No need to type 'h'. The tuning panel is visible all the time, although collapsed by default.
