### ISSUE TITLE
If a class is being renamed, save its new name on starting the rename of another class.

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#93]
If you initiate rename on one class, then type a new name (but don't hit enter), then initiate rename on a second class, it looks like you renamed the first class (the new name is shown) but the new name is not actually stored as the name of the class. So if one rename is in progress, it should be completed when another rename (or probably other actions too) start.

**Comment by nebgnahz** [comment]
Fixed by https://github.com/damellis/sensors/commit/e80bbd480d6980a5615a5417c07b0b9f612ccfbe.

Added a new `renameDone` function so that the previous renaming will be completed upon a new renaming session.
