### ISSUE TITLE
Keyboard shortcut to save training data (without having to open the save/load panel)?

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#95]
It seems weird to have to open a sub-panel with one key, then click a button to save the training data. Maybe just "s" to save training data (by prompting with the file save dialog)?

**Comment by nebgnahz** [comment]
Fixed with https://github.com/damellis/sensors/commit/ec02c9cf077dbece22593efeded04573ea123348.

Now `s` is save and `p` is for pause/resume.

Planning to get rid of the panel at some point in the future.
