### ISSUE TITLE
Add separate stage for calibrating live data based on calibration data.

### ISSUE THREAD

**Issue by damellis** [damellis/sensors#99]
Right now, the calibration data is used by an istream normalizer, which break re-calibration. (Re-calibration won't use the raw data, but will instead use data normalized based on the current / previous calibration.)

Instead, we should add a separate pipeline stage that calls the user's function for calibrating incoming data (i.e. modifying it based on the calibration data). This should happen after normalization and before feeding into the GRT pipeline proper and only if the calibration samples have been collected.

For training samples we should use calibrated data but for calibration samples we should use non-calibrated (raw) data. We should probably show calibrated data in the live stream in the training tab, but non-calibrated (raw) data in the live stream in the calibration tab.

**Comment by nebgnahz** [comment]
This latest code [1] will change `data_point` if calibrated. It will be consumed for feature extraction, sample data collection, etc. So this is separated now.

[1] https://github.com/damellis/sensors/blob/master/Xcode/SmartSensors/src/ofApp.cpp#L577
